### ISSUE TITLE
License for bsuccinct-rs

### ISSUE THREAD

**Issue by sujayakar** [beling/bsuccinct-rs#4]
hi! nice work on these crates -- I'd like to use `csf` in my (commercial) project for building perfect hash tables in index files.

would you be open to licensing this repo with an MIT license?

**Comment by beling** [comment]
All bsuccinct creates are Mit licensed - see their cargo.toml files.
Where did you find information that they use any other license?

**Comment by sujayakar** [comment]
oh whoops, I was looking for a `LICENSE` file but didn't check the `Cargo.toml`. thanks!
