### ISSUE TITLE
Zero copy run from serialized

### ISSUE THREAD

**Issue by ThomasCartier** [beling/bsuccinct-rs#7]
Hi,
Do you think it's possible to calculate the minimal hash map for some keys and later reload the function from the parameters found during the first run and provide a slice of values without copy ?

```
// this part as usual
let keys = ['a', 'b', 'z'];
let f = fmph::Function::from(keys.as_ref());

// store f somehow, serialized
// later reconstruct f from values and give it a slice of the key from memory
let f_serialized = load_serialized_data();
let f = fmph::Function::from(f_serialized, keys.as_ref());

```

That way, f can be reconstructed without all the calculations already made in the first run.

Do you see this as possible ?

I looked into the code, but not sure how to not break things.

**Comment by beling** [comment]
Only serialization with copying is possible, see:
https://docs.rs/ph/0.8.5/ph/fmph/struct.Function.html#method.write
https://docs.rs/ph/0.8.5/ph/fmph/struct.Function.html#method.read
Serialization without copying is possible to implement, but very difficult because it requires keeping the entire function in one continuous area of memory. This would require massive rework and probably sacrifice flexibility (e.g., choice of hashers, etc.).
No serialization should require keys to be given again.

**Comment by ThomasCartier** [comment]
Sorry I was not clear,
Serialization aside, this is my end goal: 

--- First run:
Calculating the indices for every values known in advance.
Retrieve the differing elements that `Function` use to calculate the indices.
Store these elements for later reuse.
Drop the function object.

-- Next runs
Recreate a new function object from the different parameters I stored earlier. I would like to be able to immediately say where the value is in the final index (not recalculated).

Because right now, We have to make as if we never calculated it before: I first have to register the array of values, again, to Function, which is slow (relatively) vs recreating Function from already pre-calculated parameters.

So are we agreeing that my need is not currently possible in your crate ?

The data set is really big so avoiding recreating Function on every object creation/usage is gold here.

**Comment by beling** [comment]
Now I understand even less. Doesn't write/read do exactly what you want? Why can't you use them?

**Comment by ThomasCartier** [comment]
Yes it would work but it still requires a lot of computation.
I will try something else.
Thanks a lot!

**Comment by beling** [comment]
Why they require a lot of computation? Are you sure you are using them correctly?

**Comment by ThomasCartier** [comment]
The read function requires lot of loads for rebuilding the object. I would have liked something faster that applies a calculation more directly: a direct calculation that gives me the slot for a given input in my oroginal keys array. 
Then it's to me to check the value there to see if it's corresponding or not and act accordingly in the flow of my code.

(Your code works just fine, it's really good.)

**Comment by beling** [comment]
I'm not sure if this is helpful, but note that Write is implemented by &mut u8, and you can call write_bytes to plan how many bytes reserve for writing function. Function does not store the keys (and does not need them for working), so you must save them separately.
https://docs.rs/ph/0.8.5/ph/fmph/struct.Function.html#method.write_bytes

**Comment by ThomasCartier** [comment]
Thanks a lot,

In the meantime, I created a small benchmark and the result seems strange.
```
#![feature(test)]
#![feature(slice_as_array)]

extern crate test;

use std::{
        collections::HashMap,
        env,
        time
};

use ph::fmph;


fn main() {

        let args: Vec<String> = env::args().collect();

        let key: u32 = args[1].as_str().parse::<u32>().unwrap();

        let loop_start = args[2].as_str().parse::<u32>().unwrap();

        let loop_end = args[3].as_str().parse::<u32>().unwrap();

        let variant: u32 = args[4].as_str().parse::<u32>().unwrap();

        let mut hash = HashMap::<u32, u32>::new();

        let mut vec = vec![];

        let mut vec_keys: Vec<u32> = vec![];

        for i in loop_start..loop_end {

                let j = test::black_box(i);

                hash.insert(j, i);

                vec.push((j, i));

                vec_keys.push(j);
        }


        let f = fmph::Function::from(vec_keys.as_slice());

        let t0 = time::Instant::now();

        let mut t1;

        if variant == 0 {

                match hash.get(&key) {
                        Some(e) => {

                                t1 = time::Instant::now();

                                println!("{}", test::black_box(e));

                                println!("{:?}", t1 - t0);
                        }
                        None => {

                                t1 = time::Instant::now();

                                println!("OUT for {}", key);

                                println!("{:?}", t1 - t0);
                        }
                };
        } else if variant == 1 {

                let mut found = false;

                for i in vec.iter() {

                        if i.0 == key {

                                found = true;

                                t1 = time::Instant::now();

                                println!("{:?}", test::black_box(i));

                                println!("{:?}", t1 - t0);

                                break;
                        }
                }

                if !found {

                        t1 = time::Instant::now();

                        println!("{:?}", t1 - t0);
                }
        } else if variant == 2 {

                match vec.binary_search_by(|data| data.0.cmp(&key)) {
                        Ok(e) => {

                                t1 = time::Instant::now();

                                println!("{:?}", test::black_box(e));

                                println!("{:?}", t1 - t0);
                        }
                        Err(_) => {

                                t1 = time::Instant::now();

                                println!("{:?}", t1 - t0);
                        }
                }
        } else {

                match f.get(&key) {
                        Some(e) => {

                                t1 = time::Instant::now();

                                println!("Yep {:?}", test::black_box(e));

                                println!("{:?}", t1 - t0);
                        }
                        None => {

                                t1 = time::Instant::now();

                                println!("{:?}", t1 - t0);
                        }
                }
        }
}

```

you can run it with `cargo run --release 2140 0 4096 3`

The last figure is the variant.
It only calculates the retrieval timing.
timing: hashmap < binary search < linear search < ph

Rust nightly.
core i7 8750h

**Comment by beling** [comment]
Micro-benchmarking is very very difficult to do correctly (mainly due to memory caching effects). Reliably measuring the time of a single read also very hard. Your program can give any result. If you have such small data (a few thousand), it's probably a waste of time to use external libraries. std::HashMap will probably be good enough.

**Comment by ThomasCartier** [comment]
No it's in the millions. 
Thanks anyway!

**Comment by ThomasCartier** [comment]
@beling : 
I retried with a much more serious input and I will use your crate.

I was thinking that we could read from a given slice: it would cut some construction cost I guess for the times the construction cost is not amortisable. Right now, multiple reads occur.

What do you think ?
Thank :+1:

**Comment by beling** [comment]
Please explain me why the read and write methods do not solve your problem? What is wrong with them?

**Comment by ThomasCartier** [comment]
It would be nice to be able to read from a slice given via network directly for example, without saving it and reading it from disk.

**Comment by beling** [comment]
read method can read from a slice of u8. write method can write to a Vec of u8 or slice of u8

**Comment by beling** [comment]
read metod can read from anything that implements Read trait, here is the list:
https://doc.rust-lang.org/std/io/trait.Read.html#implementors

**Comment by ThomasCartier** [comment]
Nice that's perfect.
Thanks a lot for this crate. Your work is great

**Comment by beling** [comment]
Good luck! And example:
https://github.com/beling/bsuccinct-rs/blob/6bd5d82c774566a59bf6be5c1e97959de43859da/ph/src/fmph/function.rs#L689
